src/accounts/urls.py
from django.urls import path
from .views import UserDetailView

app_name = 'user-api'

urlpatterns = [
    path('<slug:username>/', UserDetailView.as_view(), name='detail'),

]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from tweets.views import TweetListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TweetListView.as_view(), name='home'),
    path('tweet/', include('tweets.urls', namespace='tweet')),
    path('api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    path('profile/', include('accounts.urls', namespace='profile')),
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
]

src/tweets/api/urls.py
from django.urls import path
from .views import TweetListAPIView, TweetCreateAPIView

app_name = 'tweet-api'

urlpatterns = [
    path('', TweetListAPIView.as_view(), name='list'),
    path('create/', TweetCreateAPIView.as_view(), name='create')
]

src/tweets/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from .views import TweetDetailView, TweetListView, TweetCreateView, TweetUpdateView, TweetDeleteView

app_name = 'tweet'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('search/', TweetListView.as_view(), name='list'),
    path('create/', TweetCreateView.as_view(), name='create'),
    path('<int:pk>/', TweetDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', TweetUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', TweetDeleteView.as_view(), name='delete'),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/tweets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.exceptions import ValidationError

# Create your models here.

def validate_content(value):
    content = value
    if content == "":
        raise ValidationError('Content não pode conter espaço em branco!')
    return value

class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    content = models.CharField(max_length=140, validators=[validate_content])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse("tweet:detail", kwargs={"pk": self.pk})
    

src/tweets/forms.py
from django import forms

from .models import Tweet

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(
        attrs={ 
        'placeholder': 'your tweet',
        'class': 'form-control'}
        ))
    class Meta:
        model = Tweet
        fields = [ 'content']
    
    def clean_content(self, *args, **kwargs):
        content = self.cleaned_data.get('content')
        return content

src/accounts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView

# Create your views here.

User = get_user_model()

class UserDetailView(DetailView):
    queryset = User.objects.all()
    template_name = 'profile/profile_detail.html'

    def get_object(self):
        return get_object_or_404(User, username__iexact=self.kwargs.get('username'))
        

src/tweets/api/views.py
from rest_framework import generics, permissions
from django.db.models import Q 
from tweets.models import Tweet
from .serializers import TweetModelSerializer


class TweetCreateAPIView(generics.CreateAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()
        print(self.request.GET)
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(Q(content__icontains=query) | Q(user__username__icontains=query))
        return qs

src/tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from .models import Tweet
from .forms import TweetModelForm
from .mixins import FormUserNeededMixin, UserOwnerMixin

class TweetCreateView(FormUserNeededMixin, CreateView):
    form_class = TweetModelForm
    template_name = 'tweets/create_tweet.html'
    success_url = reverse_lazy('home')
    login_url = '/admin/'


class TweetUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    model = Tweet
    form_class = TweetModelForm
    template_name = 'tweets/update_view.html'
    success_url = '/'


class TweetDeleteView(LoginRequiredMixin, DeleteView):
    model = Tweet
    template_name = 'tweets/delete_tweet.html'
    success_url = reverse_lazy('home')

class TweetDetailView(DetailView):
    template_name = 'tweets/detail_view.html'
    model = Tweet
    

    def get_object(self):
        id = self.kwargs.get('pk')
        return Tweet.objects.get(id=id)


class TweetListView(ListView):
    template_name = "index.html"
    model = Tweet
    ordering = ['-created_at']
    

    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()
        print(self.request.GET)
        query = self.request.GET.get('q', None)
        if query is not None:
            qs = qs.filter(Q(content__icontains=query) | Q(user__username__icontains=query))
        return qs
    

    def get_context_data(self, *args, **kwargs):
        context = super(TweetListView, self).get_context_data(*args, **kwargs)
        context['create_form'] = TweetModelForm()
        context['create_url'] = reverse_lazy('tweet:create')
        return context

src/accounts/templates/profile/profile_detail.html
{% extends 'homebase.html' %}

{% block title %} {{object.first_name}} {% endblock title %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}
{% block content %}
<div class="row">
    <div class="col-sm-3 col-xs-12">
    <h1>{{object.username}}</h1>
    </div>

    <div class="col-sm-9 col-xs-12">
    <h1>Tweets</h1>
    {% for tweet in object.tweet_set.all  %}
    <p>{{tweet.content}}</p>
    <p> {{tweet.user}} | {{tweet.created_at|timesince}} </p>
    <hr/>
    
    
    
    {% endfor %}

    </div>

    
</div>

{% endblock content %}

src/tweets/templates/form.html
{% load crispy_forms_tags %}

<form  id='tweet_form' class="form mt-3 mb-3" method="POST" action="{% if action_url %}{{action_url}}{% endif %}" >
    {% csrf_token %}
    {{form|crispy}}
    <input class="btn btn-primary mt-1" type="submit" value="{{btn_title}}"/>
</form>

src/tweets/templates/homebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="TemplateMo" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet"
    />


    <title>Twitter - {% block title %}  {% endblock title %}</title>

    <!-- Bootstrap core CSS -->

    <style>
    .red-color {
      color: red;
    }

    .grey-color {
      color: #ccc;
    }
    
    </style>
  </head>

  <body>
  {% block navbar %} {% endblock  %}
    <div class='container'>
      {% block content %} {% endblock %}

    </div>
  



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% block script %}{% endblock script %}
<script>
$(document).ready(() => {
    var typingTimer;
    var doneInterval  = 800
    var searchInput = $('#navbar-search-form input[type=text')
    var searchQuery;
    
    
  searchInput.keyup((event) => { 
    searchQuery = $(event.target).val()

    clearTimeout(typingTimer)
    typingTimer = setTimeout(doneSearchTyping, doneInterval)
  })

  searchInput.keydown((event) => { 
    console.log(event.key)
    clearTimeout(typingTimer)
  })

  function doneSearchTyping() {
    if(searchQuery) {
      var url = '?q=' + searchQuery
      document.location.href = url
    }
  }



})

</script>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
{% comment %} <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
{% comment %} <script src="https://code.jquery.com/jquery-3.1.1.min.js"> {% endcomment %}
  
  </body>
</html>

src/tweets/templates/index.html
{% extends 'homebase.html' %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}
{% block title %} Início {% endblock title %}


{% block script %}

<script>
$(document).ready(function(){
    console.log('Working')
});

var charsStart = 140
var charsCurrent = 0
$('#tweet_form').append("<span id='tweetChars'>" +  charsStart  + "</span>")

$('#tweet_form textarea').keyup((event) => {
    var tweetValue = $(event.target).val()
    charsCurrent = charsStart - tweetValue.length
    var spanChars = $('#tweetChars')
    $('#tweetChars').text(charsCurrent)

    if(charsCurrent > 0) {
        spanChars.removeClass('red-color')
        spanChars.removeClass('grey-color')
    } else if(charsCurrent == 0) {
         spanChars.removeClass('red-color')
        spanChars.addClass('grey-color')
    } else if(charsCurrent < 0) {
        spanChars.removeClass('grey-color')
        spanChars.addClass('red-color')
    }

})

</script>

{% endblock script %}

{% block content %}
<div class="row">
    <div class="col-sm-3 col-xs-12" >
        <h1>{{request.user}} </h1>
    </div>

    <div class="col-sm-9">
        {% if not request.GET.q %}
    <div class="">
        {% include 'form.html' with form=create_form action_url=create_url btn_title='Tweet' %}
    </div>

{% endif %}


        {% for object in object_list %}
            <div class="media">
            {% if object.image %}
                <img class="mr-3" src="..." alt="">
            {% endif %}
                <div class="media-body">
                    {{object.content}} <br/>
                    via <a href="profile/{{object.user}}">{{object.user}}</a> |  {{object.created_at|timesince}} | <a href="{{object.get_absolute_url}}">ver</a>
                </div>
            </div> 
        <hr/>
        {% empty %}
            {% if request.GET.q %}
                <p> No tweets found. </p>
            {% else %}
                <p> No tweets yet. </p>
            {% endif %}        
        {% endfor %}

    </div>
   
</div>

{% endblock  %}

src/tweets/templates/navbar.html
<nav class="navbar navbar-light bg-light">
  <a href="{% url 'home' %}" class="navbar-brand">Navbar</a>
  {% include 'search.html' %}
</nav>

src/tweets/templates/search.html
{% block content %}
<form id='navbar-search-form' class="row row-cols-lg-auto g-3 align-items-center" method='GET' action='{% url "home" %}'>
  <div class="col-12">
    <label class="visually-hidden" for="inlineFormInputGroupUsername">Username</label>
    <div class="input-group">
      <input type="text" class="form-control" name='q' value="{{request.GET.q}}" placeholder="Faça uma busca">
    </div>
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-outline-primary">Procurar</button>
  </div>
</form>



{% endblock content %}

src/tweets/templates/tweets/create_tweet.html
{% extends 'homebase.html' %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}

{% block title %} Novo Tweet {% endblock title %}
{% block content %}
<form class='form' method='POST' action=''>
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value="Enviar"/>
</form>

{% endblock content %}

src/tweets/templates/tweets/delete_tweet.html
{% extends 'homebase.html' %}
{% block title %} Deletar {% endblock title %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}
{% block content %}
<form class='form' method='POST' action=''>
    {% csrf_token %}
    <p> Are you sure you want to delete "{{object}}"? </p>
    <input type='submit' value="Confirm"/>
</form>

{% endblock content %}

src/tweets/templates/tweets/detail_view.html
{% extends 'homebase.html' %}

{% block title %} {{tweet.content}} {% endblock title %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}
{% block content %}
<div class="row">
    {{tweet.content}} <br/>
    {{tweet.user}} <br/>
    {{tweet.created_at|timesince}} <br/>
</div>

{% endblock content %}

src/tweets/templates/tweets/update_view.html
{% extends 'homebase.html' %}

{% block title %} Atualizar {% endblock title %}
{% block navbar %} {% include 'navbar.html' %} {% endblock  %}
{% block content %}
<form class='form' method='POST' action=''>
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit' value="Atualizar"/>
</form>

{% endblock content %}